apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-proxy-pv-claim
  namespace: nginx-proxy
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
