apiVersion: v1
kind: Secret
metadata:
  name: app-mysecret
  namespace: nginx-proxy
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "683e227da04a2efbb738"
    }

#kubectl create secret generic mysecret --from-file .\golang\secrets\secret.json