apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443